services:
  db:
    image: mysql:5.7

    restart: always

    environment:
      - MYSQL_DATABASE

      # So you don't have to use root, but you can if you like

      - MYSQL_USER

      # You can use whatever password you like

      - MYSQL_PASSWORD

      # Password for root access

      - MYSQL_ROOT_PASSWORD

    ports:
      # <Port exposed> : <MySQL Port running inside container>

      - "3306:3306"

    expose:
      # Opens port 3306 on the container

      - "3306"

      # Where our data will be persisted

    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p\"${MYSQL_PASSWORD}\""]
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.8.19-management
    ports:
      - "5672:5672" # RabbitMQ default port for AMQP
      - "15672:15672" # RabbitMQ Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ts-server:
    build:
      context: ts-server
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - RABBIT_HOST=rabbitmq
      - MYSQL_HOST=db
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE


  ts-ui-dashboard:
    build: ts-ui-dashboard
    restart: always
    ports:
      - 3000:8080

# Names our volume

volumes:
  my-db:
    driver: local

  rabbitmq_data:
    driver: local
