services:
  db:
    image: mysql:5.7

    restart: always

    environment:
      MYSQL_DATABASE: "train-ticket"

      # So you don't have to use root, but you can if you like

      MYSQL_USER: "trainticket"

      # You can use whatever password you like

      MYSQL_PASSWORD: "test@123"

      # Password for root access

      MYSQL_ROOT_PASSWORD: "test@123"

    ports:
      # <Port exposed> : <MySQL Port running inside container>

      - "3306:3306"

    expose:
      # Opens port 3306 on the container

      - "3306"

      # Where our data will be persisted

    volumes:
      - my-db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.8.19-management
    ports:
      - "5672:5672" # RabbitMQ default port for AMQP
      - "15672:15672" # RabbitMQ Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ts-ui-dashboard:
    build: ts-ui-dashboard
    restart: always
    ports:
      - 3000:8080

# Names our volume

volumes:
  my-db:
    driver: local

  rabbitmq_data:
    driver: local
